### ISSUE TITLE
[공유] GoF 플라이 웨이트 패턴

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/effective-java#1]
플라이 웨이트 패턴이란?
> 객체를 가볍게 만들어 메모리 사용을 줄이는 패턴.

- 자주 변하는 속성과 변하지 않는 속성을 분리하고 재사용하여 메모리 사용을 줄일 수 있다.

Ex) Character 클래스에는 value, color, fontFamily, fontsize 라는 값이 존재한다.
fontFamily, fontsize와 같은 값은 자주 변하지 않는 속성으로 가정하면 Character 클래스는 플라이 웨이트 패턴을 적용 시킬 수 있다.

```java
//before

Character c1 = new Character("h", "white", "Nanum", 12);
Character c2 = new Character("e", "white", "Nanum", 12);
Character c3 = new Character("l", "white", "Nanum", 12);
Character c4 = new Character("l", "white", "Nanum", 12);
Character c5 = new Character("o", "white", "Nanum", 12);

//after
Character c1 = new Character('h', "white", fontFactory.getFont("nanum:12"));
Character c2 = new Character('e', "white", fontFactory.getFont("nanum:12"));
Character c3 = new Character('l', "white", fontFactory.getFont("nanum:12"));
Character c4 = new Character('l', "white", fontFactory.getFont("nanum:12"));
Character c5 = new Character('o', "white", fontFactory.getFont("nanum:12"));


public class Character {

    private char value;

    private String color;

    private Font font;

}

public class FontFactory {

    private Map<String, Font> cache = new HashMap<>();

    public Font getFont(String font) {
        if (cache.containsKey(font)) {
            return cache.get(font); //기존에 있는 font라면 객체가 생성되지 않고 재사용.
        }else {
            String[] split = font.split(":");
            Font newFont = new Font(split[0], Integer.parseInt(split[1]));
            cache.put(font, newFont);
            return newFont;
        }
    }
}

```

**Comment by hava12** [comment]
예시 추가 공유 

예시 1 ) Java의 Integer Wrapper Class 

```
public static Integer valueOf(int i) {
  if (i >= IntegerCache.low && i <= IntegerCache.high)
    return IntegerCache.cache[i + (-IntegerCache.low)];
  return new Integer(i);
}
```

int타입을 받아 Integer로 반환하는 valueOf 메소드의 경우 
각각 -128과 127인 IntegerCache.low와 IntegerCache.high 범위 내의 Integer 클래스를 미리 만들어두고 재사용합니다.

예시 2 ) String Constant Pool

![image](https://user-images.githubusercontent.com/31056938/164487234-b65b2bac-61ea-4aa9-8731-e3e7384d8a59.png)
위 사진 중 "" 따옴표를 이용해서 String 객체를 생성하는 방법을 String literal이라고 합니다.

![image](https://user-images.githubusercontent.com/31056938/164486227-2857bef1-9960-4302-af00-b66b068e844a.png)
이미지 출처 : https://starkying.tistory.com/entry/what-is-java-string-pool

String literal로 생성하면 해당 String 값은 Heap 영역 내 "String Constant Pool"에 저장되어 재사용되지만, new 연산자로 생성하면 같은 내용이라도 여러 개의 객체가 각각 Heap 영역을 차지하기 때문이다.

**Comment by woo00oo** [comment]
이해 쏙쏙 👍
