### ISSUE TITLE
[질문] 왜 자바 직렬화를 사용해야하나요?

### ISSUE THREAD

**Issue by Yunjoung808** [java-dev-study/effective-java#13]
왜죠

**Comment by woo00oo** [comment]
자바 직렬화를 사용하는 이유는 자바 시스템 내부에서 사용되는 객체 또는 데이터를 외부의 자바 시스템에서도 사용하기 위해서입니다.
이를 위해 자바 객체를 바이트 형태로 직렬화하고 바이트 형태의 데이터를 다시 자바 객체로 변환하는 역직렬화 기술을 사용하게 됩니다.
다시 말해 JVM 실행 시, 자바 객체들은 JVM 메모리 힙 영역에 위치하게 되는데 이런 자바 객체들을 외부 시스템에서 사용하기 위해 직렬화를 통해 바이트 형태로 변환 시키게 됩니다.

대표적인 예로는,  FileOutputStream, FileInPutStream 이외에도 JPA 복합키 매핑시 @IdClass에서 필수적으로 Serializable 인터페이스를 implements 해주어야 하는데 그 이유도 IdClass로 사용되는 자바 객체가 DB에서 인덱싱하는 키로 사용되기 때문에 직렬화가 가능해야 합니다.

**Comment by Jo-YeonWoo** [comment]
**Java 직렬화**
> - 객체의 내용을 byte 단위로 변환하여 파일 혹은 네트워크를 통해서 송수신이 가능하도록 하는 것
> - 자바 시스템 내부에서 사용되는 객체 또는 데이터들을 외부의 자바 시스템에서도 사용할 수 있도록 byte 형태로 변환하는 기술 + byte로 변환된 데이터를 다시 객체로 변환하는 역직렬화

**직렬화를 사용하는 이유**
1. 시스템이 다중화되어 있거나 세션 클러스터링을 통해서 세션 관리를 하는 환경에서 도메인 객체가 세션에 저장될 때 도메인 객체에 Serializable 인터페이스 클래스는 구현해야만 정상적으로 세션에서 저장하고 꺼내올 수 있음
2. 디스크에 저장하거나 통신할 때에는 값 형식 데이터만 가능
→ 사용하고 있는 데이터 통신에서 파싱할 수 있는 유의미한 데이터를 만들기 위함

위와 같은 이유로 직렬화를 사용하는데, 24p. 에서 싱클턴 클래스 직렬화에 대한 내용은 어떤 것을 위한 것인지, 어떤 맥락으로 사용된 것인지에 대해 추가적으로 아시는 분 계시면 Comment 부탁드립니다...

**Comment by woo00oo** [comment]
싱글턴 클래스를 역직렬화 시 여러 인스턴스가 생성될 수 있으니 readResolve 메서드를 추가하라는 의미 같습니다.

```java

//싱글턴
public class Elvis implements Serializable {

    public static final Elvis INSTANCE = new Elvis();

    private Elvis() {
    }

}

//클라이언트 

public static void main(String[] args) {
        try (ObjectOutput out = new ObjectOutputStream(new FileOutputStream("elvis.obj"))) {
            out.writeObject(Elvis.INSTANCE);
        } catch (IOException e) {
            e.printStackTrace();
        }

        try (ObjectInput in = new ObjectInputStream(new FileInputStream("elvis.obj"))) {
            Elvis elvis3 = (Elvis) in.readObject();
            System.out.println(elvis3 == Elvis.INSTANCE); //false가 출력(싱글턴이 깨짐)
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

```
위 코드처럼 역직렬화 시, 싱글턴이 깨지게 됩니다. 
따라서 아래 코드를 추가하여 역직렬화 시에도 싱글턴을 유지 시킬 수 있습니다.

```java

public class Elvis implements Serializable {

    public static final Elvis INSTANCE = new Elvis();

    private Elvis() {
    }

    // 역직렬화 시 새로운 인스턴스가 아닌 재정의한 readResolve 메소드가 실행됨.(위 클라이언트 코드 true 출력)
    private Object readResolve() {
        return INSTANCE;
    }

}

```

**Comment by Yunjoung808** [comment]
그냥 JSON을 쓰면 되지 않을까 생각했었는데 생각보다 쓰이는 곳이 많았군여!!

**Comment by woo00oo** [comment]
오늘날의 웹 서비스는 JSON으로 대동단결인 거 같네요ㅎㅎ
