### ISSUE TITLE
[아이템3_질문] 무상태 객체가 궁금합니다.

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/effective-java#14]
> p.23 싱글턴의 전형적인 예시로는 무상태 객체나 유일한 시스템 컴포넌트를 들 수 있다.

싱글톤 패턴을 사용할 때 무상태로 설계해야하는 이유를 알 수 있을까요?
추가적으로, 예시 코드를 볼 수 있을까요?

**Comment by woo00oo** [comment]
싱글톤 객체를 무상태로 설계하는 이유는 바로 동시성 문제 때문입니다.

싱글톤 객체는 단 하나만 JVM에 올라와 있기 때문에 모든 객체들이 싱글톤 객체를 공유하며 사용합니다.
따라서 싱글톤 객체의 인스턴스 변수들도 여러 객체에서 공유하기 때문에 동시성 문제가 발생하여 큰 장애로 이루어질 수 있습니다. 
스프링 빈 객체들도 대부분 싱글톤으로 관리되는데 이런 객체들도 무상태로 설계 해야합니다.

싱글톤 객체를 무상태로 설계하지 않으면 아래 코드처럼 동시성 문제가 발생됩니다.

```java
@Service // 싱글톤 객체
public class StatefulService {

     private int price; //상태를 유지하는 필드
   
     public void order(String name, int price) { 
          System.out.println("name = " + name + " price = " + price); 
          this.price = price; //여기가 문제!
      }

     public int getPrice() {
          return price;
     } 
}

// 클라이언트

//ThreadA: A사용자 10000원 주문 
statefulService1.order("userA", 10000);

//ThreadB: B사용자 20000원 주문 
statefulService2.order("userB", 20000);

//ThreadA: 사용자A 주문 금액 조회
int price = statefulService1.getPrice();

//ThreadA: 사용자A는 10000원을 기대했지만, 기대와 다르게 20000원 출력 
System.out.println("price = " + price);


```

**Comment by woo00oo** [comment]
추가적으로 동시성 문제를 해결하기 위해 자바에서는 ThreadLocal 이라는 클래스를 제공합니다.

**Comment by Jo-YeonWoo** [comment]
**무상태(stateless) 객체**
> 상태를 공유하는 필드 변수가 없는 것
> 지역 변수, 파라미터, ThreadLocal 등이 해당

Jasper가 작성해 준 예제 코드에 대해 부가적으로 설명하자면,
싱클톤 패턴은 하나의 객체만을 생성하고, 공유하여 사용되는데, 이때 여러 클라이언트가 `price` 값을 변경할 수 있어 문제가 발생하는 것입니다.

상태를 공유하고 있기 때문에 특정 클라이언트의 price가 보장되지 않는 것입니다.

위와 같은 이유로 무상태로 설계해야 합니다.
