### ISSUE TITLE
[질문] 방어적 복사가 무엇이며 실패 했을 경우 어떤 보안이슈로 이어지는 지 궁금합니다.

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/effective-java#15]
아이템 6 P.34 방어적 복사(defensive copy) 내용에 대해서 아래와 같이 궁금한 점이 있습니다.

1. 방어적 복사가 무엇인지? 얕은 복사와 깊은 복사와 연관이 있는 내용인지?
2. 방어적 복사에 실패하면 보안 이슈가 생길 수 있다는데 어떤 보안 이슈가 생기는 것이며, 방어적 복사에 대해서 예제 코드로 설명해주시면 감사하겠습니다.

**Comment by wnsgur9701** [comment]
먼저 얕은 복사와 깊은 복사를 간단히 그림으로 정리하면 밑에와 같습니다.   
<얕은 복사>.  
<img width="718" alt="image" src="https://user-images.githubusercontent.com/62540133/167249374-528ef61e-5686-44d3-a043-5bd8d6cb54d5.png">.  
<깊은 복사>.  
<img width="708" alt="image" src="https://user-images.githubusercontent.com/62540133/167249408-237a60a8-882e-4695-81ea-03f57089457f.png">.  

제가 생각하기에는 얕은 복사와 깊은 복사 그리고 깊은 복사를 한 카테고리 안에서 비교를 하는 것은 아니라고 생각합니다. 

얕은 복사 vs 깊은 복사.  
참조값이 같냐 다르냐를 가지고 구별.  
그래서 원본이 바뀌면 얕은 복사는 그 값이 바뀌고 깊은 복사는 그 시점의 객체를 복사해서 새로운 참조값을 생성.  
원본이 바뀌더라도 만들어진 객체는 바뀌지 않습니다.   

방어적 복사 - 방법론   
: 불변 객체로 만들고 싶은 객체가 어떠한 조작으로 인해 내부 속성의 변화의 가능성이 있을때 이를 막기 위해 원본 속성의 참조값을 가진 것들을 직접 사용하는 것이 아니라 새로운 객체를 생성하여   
객체의 불변성을 유지하도록 하는 기법     
그리고 방어적 복사를 하기 위해서 주로 사용되는 것이 깊은 복사라고 저는 이해를 했습니다.   

<방어적 복사 코드 예시>   
* 이름을 의미하는 Name class
```java
public class Name {
    private final String name;

    public Name(String name) {
        this.name = name;
    }
}
```

* List names를 인자로 받는 Names class
```java
import java.util.List;

public class Names {
    private final List<Name> names;

    public Names(List<Name> names) {
        this.names = names;
    }
}
```   
단수히 코드만을 봤을 때는 Names의 속성인 names가 final로 저장되어 있어 불변성을 유지하는 것처럼 보입니다. 하지만 주입받은 names가 외부에서 변경이 일어나면 내부 names도 같은    
참조값을 공유하고 있기 때문에 값에 있어서 변경이 일어나게 됩니다.    
```java
import java.util.ArrayList;
import java.util.List;

public class Application {
    public static void main(String[] args) {
        List<Name> originalNames = new ArrayList<>();
        originalNames.add(new Name("Fafi"));
        originalNames.add(new Name("Kevin"));
        
        Names crewNames = new Names(originalNames); // crewNames의 names: Fafi, Kevin
        originalNames.add(new Name("Sally")); // crewNames의 names: Fafi, Kevin, Sally
    }
}
```
-> crewNames의 필드인 name과 originalNames가 주소를 공유하고 있기 때문입니다.   

이제 방어적 복사를 적용해보도록 하겠습니다.   
```java
import java.util.ArrayList;
import java.util.List;

public class Names {
    private final List<Name> names;

    public Names(List<Name> names) {
        this.names = new ArrayList<>(names);
    }
}
```
이제 Names내부에서 새로운 참조값을 가진 객체를 사용하기 때문에 외부 원본 list에 변경이 있더라도 Names객체는 변경 사항이 적용되지 않습니다.   
```java
import java.util.ArrayList;
import java.util.List;

public class Application {
    public static void main(String[] args) {
        List<Name> originalNames = new ArrayList<>();
        originalNames.add(new Name("Fafi"));
        originalNames.add(new Name("Kevin"));
        
        Names crewNames = new Names(originalNames); // crewNames의 names: Fafi, Kevin
        originalNames.add(new Name("Sally")); // crewNames의 names: Fafi, Kevin
    }
}
```
하지만 이 방식 역시 문제가 있을 수 있습니다. originalNames의 객체 참조 값과 crewNames의 names 참조값은 다르지만 그 안에 있는 내부 원소들의 참조 값들은 같기 때문에   
내부 원소들의 값이 바뀌게 되면 불변성을 잃게 됩니다.   
<setter 기능이 있는 Name>.   
```java
ublic class Name {
    private String name;

    public Name(String name) {
        this.name = name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}
```   
<예시>

```java
import java.util.ArrayList;
import java.util.List;

public class Application {
    public static void main(String[] args) {
        Name crew1 = new Name("Fafi");
        Name crew2 = new Name("Kevin");
        
        List<Name> originalNames = new ArrayList<>();
        originalNames.add(crew1);
        originalNames.add(crew2);

        Names crewNames = new Names(originalNames); // crewNames의 names: Fafi, Kevin

        crew2.setName("Sally"); // crewNames의 names: Fafi, Sally
    }
}

```   
그래서 내부 원소들의 변경 가능성을 없게 setter method를 없게 만들게 할 수도 있습니다.   

그리고 보안 이슈에 관해서는 실제적인 예시를 찾아보려고 했지만 나와 있는게 없어 책에 있는 예시를 통해 설명을 하겠습니다.   
<내부 검사 로직이 있는 period class>
``` java
public final class Period {
    private final Date start;
    private final Date end;

    public Period(Date start, Date end) {
        if (start.compareTo(end) > 0) {
            throw new IllegalArgumentException("start가 end보다 늦으면 안된다");
        }
        this.start = start;
        this.end = end;
    }

    public Date getStart() { return start; }
    public Date getEnd() { return end; }
}
```
<취약 상활>
```java
Date start = new Date();
Date end = new Date();
Period p = new Period(start, end);

end.setYear(78);    // 취약점: p의 내부를 수정할 수 있다.
```
-> 처음 생성을 할 때는 내부 검사 로직을 통과 했지만 end의 수정을 통해 검사 로직이 작용하지 않는 상황 발생   
<방어>
```java
public Period(Date start, Date end) {
    this.start = new Date(start.getTime()); // defensive copy
    this.end = new Date(end.getTime());     // defensive copy
    if (this.start.compareTo(this.end) > 0) {
        throw new IllegalArgumentException("start가 end보다 늦으면 안된다");
    }
}
```
-> Period 내부 필드에 직접 객체를 주입하는 것이 아니라 깊은 복사를 사용하여 객체를 방어적으로 복사하기 때문에 외부에서 start와 end에 대해 값이 수정되었다고 하더라도 Period내부에   
값들은 수정이 되지 않습니다.   

추가로 궁금하신 내용 있으면 알려주세요!

**Comment by wnsgur9701** [comment]
> 아이템 6 P.34 방어적 복사(defensive copy) 내용에 대해서 아래와 같이 궁금한 점이 있습니다.
> 
> 1. 방어적 복사가 무엇인지? 얕은 복사와 깊은 복사와 연관이 있는 내용인지?
> 2. 방어적 복사에 실패하면 보안 이슈가 생길 수 있다는데 어떤 보안 이슈가 생기는 것이며, 방어적 복사에 대해서 예제 코드로 설명해주시면 감사하겠습니다.

**Comment by wnsgur9701** [comment]
> 아이템 6 P.34 방어적 복사(defensive copy) 내용에 대해서 아래와 같이 궁금한 점이 있습니다.
> 
> 1. 방어적 복사가 무엇인지? 얕은 복사와 깊은 복사와 연관이 있는 내용인지?
> 2. 방어적 복사에 실패하면 보안 이슈가 생길 수 있다는데 어떤 보안 이슈가 생기는 것이며, 방어적 복사에 대해서 예제 코드로 설명해주시면 감사하겠습니다.

**Comment by wnsgur9701** [comment]
먼저 얕은 복사와 깊은 복사를 간단히 그림으로 정리하면 밑에와 같습니다.   
<얕은 복사>.  
<img width="718" alt="image" src="https://user-images.githubusercontent.com/62540133/167249374-528ef61e-5686-44d3-a043-5bd8d6cb54d5.png">.  
<깊은 복사>.  
<img width="708" alt="image" src="https://user-images.githubusercontent.com/62540133/167249408-237a60a8-882e-4695-81ea-03f57089457f.png">.  

제가 생각하기에는 얕은 복사와 깊은 복사 그리고 깊은 복사를 한 카테고리 안에서 비교를 하는 것은 아니라고 생각합니다. 

얕은 복사 vs 깊은 복사.  
참조값이 같냐 다르냐를 가지고 구별.  
그래서 원본이 바뀌면 얕은 복사는 그 값이 바뀌고 깊은 복사는 그 시점의 객체를 복사해서 새로운 참조값을 생성.  
원본이 바뀌더라도 만들어진 객체는 바뀌지 않습니다.   

방어적 복사 - 방법론   
: 불변 객체로 만들고 싶은 객체가 어떠한 조작으로 인해 내부 속성의 변화의 가능성이 있을때 이를 막기 위해 원본 속성의 참조값을 가진 것들을 직접 사용하는 것이 아니라 새로운 객체를 생성하여   
객체의 불변성을 유지하도록 하는 기법     
그리고 방어적 복사를 하기 위해서 주로 사용되는 것이 깊은 복사라고 저는 이해를 했습니다.   

<방어적 복사 코드 예시>   
* 이름을 의미하는 Name class
```java
public class Name {
    private final String name;

    public Name(String name) {
        this.name = name;
    }
}
```

* List names를 인자로 받는 Names class
```java
import java.util.List;

public class Names {
    private final List<Name> names;

    public Names(List<Name> names) {
        this.names = names;
    }
}
```   
단수히 코드만을 봤을 때는 Names의 속성인 names가 final로 저장되어 있어 불변성을 유지하는 것처럼 보입니다. 하지만 주입받은 names가 외부에서 변경이 일어나면 내부 names도 같은    
참조값을 공유하고 있기 때문에 값에 있어서 변경이 일어나게 됩니다.    
```java
import java.util.ArrayList;
import java.util.List;

public class Application {
    public static void main(String[] args) {
        List<Name> originalNames = new ArrayList<>();
        originalNames.add(new Name("Fafi"));
        originalNames.add(new Name("Kevin"));
        
        Names crewNames = new Names(originalNames); // crewNames의 names: Fafi, Kevin
        originalNames.add(new Name("Sally")); // crewNames의 names: Fafi, Kevin, Sally
    }
}
```
-> crewNames의 필드인 name과 originalNames가 주소를 공유하고 있기 때문입니다.   

이제 방어적 복사를 적용해보도록 하겠습니다.   
```java
import java.util.ArrayList;
import java.util.List;

public class Names {
    private final List<Name> names;

    public Names(List<Name> names) {
        this.names = new ArrayList<>(names);
    }
}
```
이제 Names내부에서 새로운 참조값을 가진 객체를 사용하기 때문에 외부 원본 list에 변경이 있더라도 Names객체는 변경 사항이 적용되지 않습니다.   
```java
import java.util.ArrayList;
import java.util.List;

public class Application {
    public static void main(String[] args) {
        List<Name> originalNames = new ArrayList<>();
        originalNames.add(new Name("Fafi"));
        originalNames.add(new Name("Kevin"));
        
        Names crewNames = new Names(originalNames); // crewNames의 names: Fafi, Kevin
        originalNames.add(new Name("Sally")); // crewNames의 names: Fafi, Kevin
    }
}
```
하지만 이 방식 역시 문제가 있을 수 있습니다. originalNames의 객체 참조 값과 crewNames의 names 참조값은 다르지만 그 안에 있는 내부 원소들의 참조 값들은 같기 때문에   
내부 원소들의 값이 바뀌게 되면 불변성을 잃게 됩니다.   
<setter 기능이 있는 Name>.   
```java
ublic class Name {
    private String name;

    public Name(String name) {
        this.name = name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}
```   
<예시>

```java
import java.util.ArrayList;
import java.util.List;

public class Application {
    public static void main(String[] args) {
        Name crew1 = new Name("Fafi");
        Name crew2 = new Name("Kevin");
        
        List<Name> originalNames = new ArrayList<>();
        originalNames.add(crew1);
        originalNames.add(crew2);

        Names crewNames = new Names(originalNames); // crewNames의 names: Fafi, Kevin

        crew2.setName("Sally"); // crewNames의 names: Fafi, Sally
    }
}

```   
그래서 내부 원소들의 변경 가능성을 없게 setter method를 없게 만들게 할 수도 있습니다.   

그리고 보안 이슈에 관해서는 실제적인 예시를 찾아보려고 했지만 나와 있는게 없어 책에 있는 예시를 통해 설명을 하겠습니다.   
<내부 검사 로직이 있는 period class>
``` java
public final class Period {
    private final Date start;
    private final Date end;

    public Period(Date start, Date end) {
        if (start.compareTo(end) > 0) {
            throw new IllegalArgumentException("start가 end보다 늦으면 안된다");
        }
        this.start = start;
        this.end = end;
    }

    public Date getStart() { return start; }
    public Date getEnd() { return end; }
}
```
<취약 상활>
```java
Date start = new Date();
Date end = new Date();
Period p = new Period(start, end);

end.setYear(78);    // 취약점: p의 내부를 수정할 수 있다.
```
-> 처음 생성을 할 때는 내부 검사 로직을 통과 했지만 end의 수정을 통해 검사 로직이 작용하지 않는 상황 발생   
<방어>
```java
public Period(Date start, Date end) {
    this.start = new Date(start.getTime()); // defensive copy
    this.end = new Date(end.getTime());     // defensive copy
    if (this.start.compareTo(this.end) > 0) {
        throw new IllegalArgumentException("start가 end보다 늦으면 안된다");
    }
}
```
-> Period 내부 필드에 직접 객체를 주입하는 것이 아니라 깊은 복사를 사용하여 객체를 방어적으로 복사하기 때문에 외부에서 start와 end에 대해 값이 수정되었다고 하더라도 Period내부에   
값들은 수정이 되지 않습니다.   

추가로 궁금하신 내용 있으면 알려주세요!

**Comment by wnsgur9701** [comment]
> 아이템 6 P.34 방어적 복사(defensive copy) 내용에 대해서 아래와 같이 궁금한 점이 있습니다.
> 
> 1. 방어적 복사가 무엇인지? 얕은 복사와 깊은 복사와 연관이 있는 내용인지?
> 2. 방어적 복사에 실패하면 보안 이슈가 생길 수 있다는데 어떤 보안 이슈가 생기는 것이며, 방어적 복사에 대해서 예제 코드로 설명해주시면 감사하겠습니다.
