### ISSUE TITLE
[아이템6_질문] 유한상태머신이 궁금합니다.

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/effective-java#16]
> p.32 Pattern은 입력받은 정규표현식에 해당하는 유한상태머신을 만들기 때문에 인스턴스 생성 비용이 높다.

이 문장에서 의미하는 유한상태머신이라는게 어떤 걸 의미하는걸까요??
상태의 수가 유한한 기계라고 하셨는데 이해가 잘 안됩니다!

**Comment by wnsgur9701** [comment]
유한 상태 머신의 과정   

유한상태머신은 알고리즘 디자인을 위해서 사용하는 수학적 도구입니다. 간단히 설명하자면 상태머신은   
1. 일련의 입력을 읽는다.   
2. 입력을 읽어서 다른 상태로 전환 한다.    
3. 전환할 상태를 지정하는 간단한 일을 한다.   

한 가지 상황을 가정해 보면 더 이해가 쉽습니다.    
저희는 문자열이 어떠한 규칙을 따르는지 확인하기 위해 유한 가상 머신을 사용합니다.   
* 문자열이 @로 시작하여 #으로 끝나고 그 안에는 숫자가 온다.    
ex) @12345# , @1#, @2134#, @223#@2313#     
<img width="438" alt="image" src="https://user-images.githubusercontent.com/62540133/167415168-d45c6be6-ab74-4759-913e-0c6824b5a530.png">
   
     
* 코드 구성
* 1. 처음 상태는 0
* 2. 각 문자열을 검사하면서 조건에 맞으면 다른 상태로 이동
* 3. 그래서 결국 최종 상태가 3이면 true 아니면 false를 반환   
이를 코드로 구성하면 밑에와 같이 유한 상태 머신을 만들 수 있습니다.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/62540133/167416058-cb486086-5d61-42b8-bc26-f3216fc50280.png">
<img width="303" alt="image" src="https://user-images.githubusercontent.com/62540133/167416188-393d4cbb-2a6b-4532-a45c-21545d0ef1d2.png">
