### ISSUE TITLE
[질문] 박싱된 기본타입

### ISSUE THREAD

**Issue by Yunjoung808** [java-dev-study/effective-java#18]
p.34 "박싱된 기본 타입" 에서 박싱됐다는 표현이 어떤 의미인가요?

**Comment by im-Lily** [comment]
자바의 데이터 타입은 크게 기본 타입(Primitive type)과 참조 타입(Reference type)으로 구분할 수 있습니다.

![8850AEAA-D2A9-4F39-A5D2-637FAF4000D8](https://user-images.githubusercontent.com/67992684/167518538-d0107d08-e301-4c4c-9a20-97a52a92b85e.png)
위 그림에서 볼 수 있듯 기본 타입에 대응되는 참조 타입이 하나씩 있으며, 이를 박싱된 기본 타입이라고 합니다.

래퍼 클래스를 사용하는 이유는 다음과 같습니다.
1. 기본 데이터 타입을 Object로 변환할 수 있습니다.
2. ArrayList 등과 같은 Collection Framework의 데이터 구조는 기본 타입이 아닌 객체만 저장하여 래퍼 클래스를 사용하여 박싱/언박싱이 발생한다.
![8194027C-602A-4FDB-B91E-A8ACFAFB11D5](https://user-images.githubusercontent.com/67992684/167518560-a6aca1b7-33e0-4276-b8c5-edde9cf0fc9f.png)
3. 멀티 스레드에서 동기화를 지원하려면 객체가 필요하다.

여기서 말하는 박싱(boxing)은 기본 자료형의 데이터를 래퍼 클래스의 객체로 만드는 과정을 의미하고, 언박싱(unboxing)은 래퍼 클래스의 데이터를 기본 자료형으로 얻어내는 과정을 말합니다. 
![A6EB8148-4177-4ED7-A154-6F58D014F32D](https://user-images.githubusercontent.com/67992684/167518580-ca730cef-faf0-4ace-b861-e91ed953acf8.png)
