### ISSUE TITLE
[질문] java.lang.ref의 활용법에 대해 듣고싶습니다

### ISSUE THREAD

**Issue by Yunjoung808** [java-dev-study/effective-java#20]
p.39 에 나오는 java.lang.ref을 직접 활용해서 더 복잡한? 캐시를 만들 수 있다고 나오는데
어떻게 활용할 수 있을까요?

**Comment by wnsgur9701** [comment]
Java의 참조 유형에는 크게 4가지가 있습니다.
참조 유형에 따라 GC 실행 대상여부, 시점이 달라집니다.

Strong References (강한 참조)

Soft References (소프트 참조)

Weak References (약한 참조)

Phantom References (팬텀 참조)

(강한 참조)
image
-> g 변수가 참조를 가지고 있는 한, Gfg객체는 GC의 대상이 되지 않습니다

(소프트 참조).
image
-> 대상 객체를 참조하는 경우가 softReference 객체만 존재하는 경우 gc의 대상이 된다.
단, jvm의 메모리가 부족한 경우에만 힙영역에서 제거되고 메모리가 부족하지 않다면 굳이 제거하지 않습니다.

(약한 참조)
image
-> 대상 객체를 참조하는 경우가 WeakReferences 객체만 존재하는 경우 GC의 대상이 됩니다.
다음 GC 실행시 무조건 힙 메모리에서 제거됩니다.

(팬텀 참조)   
일단은 pass...

이번 발표 자료의 내용 부분입니다. 각 참조를 보시면, 참조 유형에 따라 Garbage Collection에 대상이 되는 경우가 다릅니다. 이러한 상황에 맞춰 cache에서도 제가 만약 메모리가 부족했을 때만 참조된 객체를 제거하는 cache를 만들고 싶으면 soft 참조를 사용하면 되고, 그때 그때 참조된 객체를 제거하고 싶은 cache를 만들고 싶으면 약한 참조를 사용하시면 됩니다. 이러한 상황이 참조를 이용한 더 복잡한 캐시가 아닐까 생각이 듭니다!
