### ISSUE TITLE
[질문] 생성 비용이 비싼 객체

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/effective-java#21]
생성 비용이 비싸다는 것은 성능적인 측면에서 메모리, 소요 시간 등이 많이 들어간다는 것을 뜻하는 게 맞나요?
'생성 비용이 비싼' 객체의 정확한 의미와 생성 비용을 줄일 수 있는 방법에는 추가적으로 무엇이 더 있나요?

**Comment by wnsgur9701** [comment]
비싼 객체라는 것은 인스턴스를 생성하는데 드는 비용이 크다는 의미입니다. 
→ 메모리, 디스크 사용랑, 대역폭 등이 높을수록 생성 비용이 비싸다는 이야기를 합니다. 
보통 Connection, Pattern 인스턴스들이 비싼 객체로 소개됩니다. 

생성 비용을 줄일 수 있는 방법에는 필요할 때마다 생성하지 않고 생성한 것을 여러 번 이용하는 것이 유일하다는 생각이 듭니다. 이에 대한 예시로는 connection pool과 같이 생성할 수를 미리 정해놓고 재사용하는 것 밖에는 생각이 나질 않네요...   
다른 분들 추가적인 의견 있으면 알려주세요!
