### ISSUE TITLE
[질문] 네이티브 피어

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/effective-java#24]
네이티브 피어에 대한 설명과 네이티브 객체 예시 및 네이티브 피어가 포함된 close 메서드 사용 코드 예시를 볼 수 있을까요?

**Comment by hava12** [comment]
자바의 런타임 데이터 영역은 아래와 같이 5가지로 구성되어 있습니다.

---

![image](https://user-images.githubusercontent.com/31056938/168479462-be49e6a2-6a00-45e5-ae39-c5f7088599a6.png)

---
**Method Area**: 클래스, 변수, 메소드, static 변수, 상수 정보(Runtime Constant Pool) 등이 저장되는 영역이다.
(모든 thread가 공유한다. JVM이 시작될 때 생성된다.)

**Heap Area**: new 명령어로 생성된 인스턴스와 Array 객체가 저장되는 구역이다. GC가 발생하는 부분이다. 거꾸로 말하면, Heap Area가 아닌 나머지 영역은 GC의 대상이 아니다.
(모든 thread가 공유한다. JVM이 시작될 때 생성된다.)

**Stack Area**: thread가 시작할 때 생성된다. 메소드 내에서 사용되는 값들(매개변수, 지역변수, 리턴값 등)이 저장되는 구역으로, 메소드가 호출될 때 LIFO(혹은 FILO)로 'stack frame'이 하나씩 생성되고, 메소드 실행이 완료되면 스택에서 지워진다.
(각 thread별로 하나씩 생성된다.)

**PC Register**: Java의 thread들은 각자의 PC register를 가진다. 이 곳에는 현재 수행 중인 JVM의 인스트럭션의 주소값이 보관된다. CPU의 register와 역할이 비슷하다.
(각 thread별로 하나씩 생성된다.)

**Native Method Stack**: Java 이외의 다른 언어의 메소드 호출을 위해 할당되는 구역으로, 언어에 맞게 스택이 형성된다.
(각 thread별로 하나씩 생성된다.)

위 설명에 따르면 Heap Area를 제외한 메모리 영역은 GC의 대상이 되지 않습니다.

그러나 JNI(Java Native Interface)를 통해 호출된 메서드는 Native Method Stack에 저장됩니다. (GC 대상이 되지 않음)


예시 
```
class HelloWorld
{
	private native void print();
	public static void main(String[] args)
	{
		new HelloWorld().print();
	}
	static{
		System.loadLibrary("HelloWorld");
	}
}
```
위처럼 native예약어를 통해 C나 C++ 라이브러리에 메소드의 기능을 위임한 객체를 네이티브 피어라고 하는 것으로 보입니다.

---

예시는 '**ServerSocket** 클래스 및 **SocketImpl**클래스의 예시를 들겠습니다.
ServerSocket클래스는 TCP서버의 역할을 하는 클래스입니다.
SocketImpl클래스는 소캣을 구현하는 모든 클래스의 공통 슈퍼클래스라고 합니다.

 ServerSocket의 기본 생성자를 살펴보면 아래와 같습니다.
![image](https://user-images.githubusercontent.com/31056938/168480921-05a9074c-b779-4c42-9c71-3790efc354e7.png)
![image](https://user-images.githubusercontent.com/31056938/168480945-9b535626-bc7f-40a9-b683-be64669bca1e.png)

SocketImplFactory 가 null이라고 가정하면 SocksSocketImpl 인스턴스를 생성하게 됩니다.

SockSocketImpl클래스 중 close메소드를 보면 super클래스의 close()를 호출하는 것을 볼 수 있습니다.
![image](https://user-images.githubusercontent.com/31056938/168481246-9aaafabf-822c-4208-8240-cfd0335b6b9c.png)

부모 클래스인 AbstractPlainSocketImpl 클래스의 close() 메소드를 보면 
socketClose() 라는 메소드를 호출하며 해당 메소드 내에서는 socketClose0 이라는 메소드를 호출합니다. (close -> socketClose -> socketClose0)
![image](https://user-images.githubusercontent.com/31056938/168482484-6cba2dd8-6428-486a-bebf-af7070c4008a.png)
![image](https://user-images.githubusercontent.com/31056938/168482598-7454ce6e-2cef-47ed-84d6-801cbb7a8232.png)

* SocketClose0 의 주석에 file descriptor를 release해준다는 것을 보니 해당 기능을 native 메소드로 수행하는 것으로 보입니다.
* **File Descriptor란 ?** 리눅스 운영체계에서 파일에 대한 정보를 기술하고 유지하는 기억장치의 영역

socketClose0는 추상 메서드로 선언되어 있는데 AbstractPlainSocketImpl클래스를 상속받은 PlainSocketImpl클래스의 socketClose0 구현을 살펴보면 또 close0 메소드를 호출합니다.. 복잡하네요.. 
![image](https://user-images.githubusercontent.com/31056938/168481975-966617c2-3b1e-464b-953e-81024f13bff9.png)

close0 메소드는 native 메소드로 구성되어 있습니다. (해당 부분에서 File Descriptor를 release해 주는 것으로 보입니다.)
![image](https://user-images.githubusercontent.com/31056938/168482002-7f7f443c-472c-427e-ad22-a34a2b0c43b3.png)

위 코드를 토대로 ServerSocket이 close될 때 SocketImpl를 상속받은PlainSocketImpl클래스의 native 메소드인 close0메소드를 호출하여 GC가 정리하지 못하는 네이티브 피어 메모리를 정리하는 것이 아닐까 추측해봅니다.. 

* 소스를 따라가면서 추측한 내용이라 틀린 정보가 있을 수 있습니다. 더 아시는 분이 계신다면 부가설명 부탁드립니다. 
* 추가적인 내용 또는 수정사항 있으면 공유하겠습니다.

출처: 
- [https://starkying.tistory.com/entry/JVM-아키텍처와-Garbage-Collection-기초-요약](https://starkying.tistory.com/entry/JVM-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98%EC%99%80-Garbage-Collection-%EA%B8%B0%EC%B4%88-%EC%9A%94%EC%95%BD) [Random Access Memories]
-https://ko.wikipedia.org/wiki/%EC%9E%90%EB%B0%94_%EB%84%A4%EC%9D%B4%ED%8B%B0%EB%B8%8C_%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4
- https://love-every-moment.tistory.com/45
