### ISSUE TITLE
[질문] 예외 처리

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/effective-java#25]
48p에 '두 번째 예외가 첫 번째 예외를 완전히 집어삼켜 스택 추적 내역에 첫 번째 예외에 관한 정보는 남지 않는다' 라는 문장과 
49p에 '숨겨진 예외들도 그냥 버려지지는 않고, 스택 추적 내역에 '숨겨졌다(suppressed)'는 꼬리표를 달고 출력된다' 라는 문장이 기재되어 있는데, 각각의 문장에 대해 스택 추적 내역을 볼 수 있는 방법엔 어떤 게 있나요?
또한, 스택 추적 내역을 볼 수 있다면, 관련 예시를 같이 볼 수 있을까요?

**Comment by hava12** [comment]
2가지에 대한 예시를 직접 만들어서 볼 수 있습니다.
우선 close 도중 예외가 발생하도록 ClosaeableObject라는 클래스를 만들고 AutoCloseable 인터페이스를 상속받은 후 오버라이딩한 close() 메소드내에 RuntimeException을 발생시킵니다.
```
public class CloseableObject implements AutoCloseable {
	public String business() {
		return "수행";
	}
	@Override
	public void close() throws Exception {
		throw new RuntimeException("예외발생");
	}
}

```
**1번째**. Try Finally Case에서 첫 번째 예외에 관한 정보가 남지 않는 경우의 예시입니다.
```

// Try Finally Case
CloseableObject closeable = new CloseableObject();
try {
	System.out.println("비즈니스 수행 : " + closeable.business());
	throw new RuntimeException("Error");
} finally {
	closeable.close();
}

```
위처럼 소스를 작성하게 되면 try블록 내에서 RuntimeException이 발생하고 finally블록에서 close할 때 또 한번 에러가 발생하게 됩니다. 
이 때 스택 추적 내용을 살펴보면 
![image](https://user-images.githubusercontent.com/31056938/168695622-d4b1dc32-3c3f-4a15-bb8f-6f5c2b6fb23a.png)
위처럼 표시되며 finally블록 안에서 발생한 예외에 대한 스택만 표시되는 것을 확인할 수 있습니다.

**2번째**. Try with Resource 케이스를 살펴보겠습니다.
```
// Try with resource Case
try ( CloseableObject closeableObject = new CloseableObject()) {
	System.out.println("비즈니스 수행 : " + closeableObject.business());
	throw new RuntimeException("Error");
}
```
위와 같은 소스를 try with resource를 이용해 작성한 예제입니다. 
같은 방식으로 try블록 안에서 RuntimeException이 발생하고 close하는 중에 또 한번 RuntimeException이 발생할 것입니다.
결과를 확인해 보겠습니다.
![image](https://user-images.githubusercontent.com/31056938/168695900-becdf52b-ed26-4a8f-83d0-3214ecbc0fb9.png)
위처럼 close 메서드 내에서 발생한 RuntimeException은 Suppressed처리되어 하단에 표시되는 것을 알 수 있습니다.

**Comment by im-Lily** [comment]
빠르게 커멘트 남겨주셨네요👍

**Comment by Jo-YeonWoo** [comment]
아 콘솔 창에 출력되는 스택 트레이스가 스택 추적 내역이네요...!
책을 읽으면서 그 생각을 못 하고 다른 방법이나 확인 가능한 툴 같은 게 있는 줄 알았어요
다들 감사합니다 👍
