### ISSUE TITLE
[질문] try-with-resources 예제 코드

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/effective-java#26]
48~49p에 기재된 try-with-resources를 사용한 예제 코드들에 대해 어느 부분에서 try-with-resources가 어떻게 쓰인 건지 코드가 잘 이해가 되지 않는데 설명해 주실 수 있나요..?

**Comment by im-Lily** [comment]
JDK 1.7부터 try-with-resources문이 추가되었습니다. 
먼저, try-catch문의 예시를 보여드리겠습니다.
```java
try {
    fis = new FileInputStream("score.text");
    dis = new DataInputStream("fis");
} catch (IOExceiption ie) {
    ie.printStackTrace();
} finally {
    dis.close(); 
}
```
위 코드는 DataInputStream을 사용해서 파일로부터 데이터를 읽는 코드로, 데이터를 읽는 도중에 예외가 발생하더라도 DataInputStream이 닫히도록 finally 블록 안에 close()를 넣었습니다.
그러나, 위 코드는 close()가 예외를 발생시킬 수 있기 때문에 문제가 있습니다. 변경된 코드는 다음과 같습니다.
```java
try {
    fis = new FileInputStream("score.txt");
    dis = new DataInputStream("fis");
} catch (IOExceiption ie) {
    ie.printStackTrace();
} finally {
    try {
        if(dis != null) {
            dis.close();
    } catch (IOException ie) {
            ie.printStackTrace();
    }
}
```
fianlly 블록 안에 try-catch문으로 close()에서 발생할 수 있는 예외를 처리했지만 코드가 복잡해졌습니다. 이를 개선하기 위해 try-with-resources문이 추가되었습니다.
```java
try(FileInputStream fis = new FileInputStream("score.txt");
    DataInputStream dis = new DataInputStream(fis)) {
    while(true) {
        score = dis.readInt();
        System.out.println(score);
        sum += score;
    }
} catch (EoFException e) {
    System.out.println("점수는 " + sum);
} catch (IOException ie) {
    ie.printStackTrace();
}
```
try-with-resources문의 괄호()안에 객체를 생성하는 문장을 넣으면, 이 객체는 따로 close()를 호출하지 않아도 try 블록을 벗어나는 순간 자동적으로 close()가 호출됩니다. 이 때, close()가 호출되는 것은 AutoCloseable을 구현한 객체에만 해당이 됩니다. 
이처럼 try-with-resources문을 사용하면 코드를 짧고 간결하게 만들어 읽기 쉽고 유지보수가 쉬워지는 것을 알 수 있습니다.

**Comment by woo00oo** [comment]
try-with-resources가 사용된 클래스의 클래스 파일을 확인 해보시면 
close() 처리를 어떻게 해주는지, 스택트레이스에서 Suppressed 처리는 어떻게 해주는지 코드상으로 확인하실 수 있습니다~
