### ISSUE TITLE
[질문] 책 53p 값 클래스 VO

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/effective-java#27]
업무 소스 코드 상에서 VO를 설계해 개발하시는 분 있으실까요?
사용 사례에 대해서 공유 해주시면 감사하겠습니다.(어떤 상황에서 VO를 사용하는지)

주워 듣기론.. DDD에서 언급되는 VO를 설계할때 아래와 같이 설계를 한다고 들었습니다. 
int money에서 class Money로 변환하면 어떤 장점들이 존재하는지 궁금하네요.

```java
private int money;

//DDD
public class Money {
    private final int value;
}

```

**Comment by hava12** [comment]
저도 사용하려고 노력중이지만 적당한 예시는 없어서 .. 책에서 봤던 내용만 조금 적어보겠습니다.

해당 데이터의 기능을 명확하게 표시하고, VO를 위한 기능을 추가하여 코드를 이해하는데 도움이 되는 부분이 장점이라고 보면 될 것 같습니다.

코드를 예시로 들자면

금액을 기본형 타입으로 사용하는 경우
```
public class Order {
    private int price;
    private int quantiry;

    private int calculateAmount() {
        return price*quantity;
    }
}
```

 금액을 VO로 사용하는 경우
```
public class Order {
    private Money price;
    private int quantity;

    private Money calculateAmount() {
        return price.multiply(quantity);
    }
}

Money {
    private int value;

    public Money getValue(){...}

    public Money add(Money money) {
        // 기본적으로 VO 객체는 불변이기 때문에 새로운 인스턴스를 반환한다.
        return new Money(this.value + money.value);
    }

   public Money multiply(int quantity) {
       return new Money(this.value * quantity);
   }
}
```

위를 보면 price가 단순히 정수형 int값이 아닌 돈을 의미한다는 것을 명확하게 보여줄 뿐 아니라 add, multyply등의 기능을 추가할 수 있다는 것을 알 수 있습니다.
