### ISSUE TITLE
[아이템 10_질문] 객체 식별성과 논리적 동치성

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/effective-java#28]
> p.53 객체 식별성이 아니라 논리적 동치성을 확인해야 한다.

객체 식별성은 객체의 주소값을, 논리적 동치성은 값 자체의 비교를 의미하는게 맞을까요?

```java
class Example {
    private int num;

    Example(int n) {
        this.num = n;
    }
}

Example e1 = new Example(22);
Example e2 = new Example(22);

이 둘은 서로 다른 주소값을 참조하고 있어서 같은 객체라고 볼 수 없지만, 값이 동일하니 논리적 동치성 즉, 동일한 상태를 갖는다 라고 이해하면 될까요?

**Comment by hava12** [comment]
네 맞습니다.
백기선님의 강의 예시를 따르면 

지폐가 두 장이 있을 때,
두 개의 지폐 에 대한 고유 번호를 비교하는 것은 객체의 식별성을 확인하는 것
지폐의 금액을 확인하여 일치 여부를 비교하는 것은 논리적 동치성을 확인하는 것

위와 같이 생각해보면 편할 것 같습니다.
