### ISSUE TITLE
[질문] 신뢰할 수 없는 자원, 결정적 계산

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/effective-java#29]
61p.에 기재된 내용 중 `equals의 판단에 신뢰할 수 없는 자원이 끼어들게 해서는 안 된다.` 라는 문장에 대해 감이 잘 오지 않는데 혹시 관련된 내용에 대해 어떤 의미로 사용된 건지 알 수 있을까요...?

또한, `메모리에 존재하는 객체만을 사용한 결정적(deterministic) 계산`에 대한 내용이 잘 안 나오는 것 같은데 알고 계시는 내용이 있으시면 설명 부탁드립니다!

**Comment by hava12** [comment]
신뢰할 수 없는 자원이 끼어들게 해서 안된다는 내용은 책에서 나온 내용처럼 네트워크를 통하여 값을 가져오는 경우처럼 값이 항상 일치함을 보장할 수 없는 자원의 개입을 하지 말라는 의미로 해석됩니다.
외부 네트워크를 호출한 값을 equals 비교하는 경우 외부 네트워크의 변경으로 인하여 일관성이 유지되기 어렵기 때문입니다.

아래 메모리에 존재하는 객체만을 사용한 결정적 계산이라는 의미도 같은 의미로 보실 수 있을 것 같습니다.
외부 자원의 호출을 최소화하고 신뢰할 수 있는 내부 자원을 사용하라는 의미로 보입니다.
