### ISSUE TITLE
[공유] 서비스 제공자 프레임워크

### ISSUE THREAD

**Issue by hava12** [java-dev-study/effective-java#3]
### **서비스 제공자 프레임워크**

JDBC에서 드라이버를 등록할 때 일반적으로
`DriverManager.registerDriver(new Driver());` 
위처럼 사용하지 않고
 `Class.forName("com.mysql.cj.jdbc.Driver")` 처럼 Reflection을 사용해 Driver클래스를 로드합니다.

이유는 com.mysql.cj.jdbc.Driver 클래스 로딩 시 static영역에서 registerDriver 정적 메소드를 호출하기 때문입니다.
![image](https://user-images.githubusercontent.com/31056938/164910301-44f998d2-7bb0-450b-b24d-aec17ddd6196.png)

계속..

**Comment by maggggggggggggie** [comment]
![서비스 제공자 인터페이스의 구성 ](https://user-images.githubusercontent.com/103933027/164969339-26127fde-fe09-4656-b6af-5566f68a351f.png)

- Connection, Driver 라는 두개의 인터페이스를 제공합니다.
- DriverManager 클래스를 통해 Connection을 얻을 수 있습니다.

![서비스 접근 API ](https://user-images.githubusercontent.com/103933027/164969409-f1fb84b4-d29e-44be-88ed-0bd73c7617d7.png)

- API를 이용하는 클라이언트 쪽에서는 위처럼  `DriverManager의 getConnection()` , `getConnection(String name)`  을 통해 원하는 Connection을 얻을 수 있습니다.

위와 관련해서 추가적으로 찾아보니, Driver 클래스의 API 안의 요런 내용이 있다고 합니다. 
`When a Driver class is loaded, it should create an instance of itself and register it with the DriverManager. This means that a user can load and register a driver by calling
   Class.forName(String name)` 

즉, 자바 가상머신이 동작을 시작하고, 코드가 실행되기 전까지는 어떤 JDBC 드라이버가 사용될 지 모르기 때문에, 동적으로 드라이버를 로딩하기 위해 리플렉션(java.lang.reflect)을 이용한다고 합니다. 

찾아보니까 리플렉션을 쓰는 경우가 다양한 것 같은데 .. ^^ ..

**Comment by woo00oo** [comment]
#### 리플렉션이란? 
>  JVM 클래스 로더를 통해 읽어온 클래스 정보를 사용하는 기술.
리플렉션을 사용해 클래스를 읽어오거나, 인스턴스를 만들거나, 메소드를 실행하거나, 필드의 값을 가져오거나 변경하는 것이 가능하다.

#### 간단한 리플렉션 사용 코드 예시

```java

public Class Hello() {
    public String hi() {
        System.out.println("hello"); 
    }
}

// 리플렉션 API 
Class<?> helloClass = Class.forName("FQCN") // 클래스가 속한 패키지명을 모두 포함한 이름
Constructor<?> constructor = aClass.getConstructor();
Hello hello = (Hello) constructor.newInstance();
hello.hi();

// 실행 결과
// hello

```


#### 리플렉션은 언제 사용될까?
Java 리플렉션은 우리가 코딩을 하면서 직접 사용하는 일은 극히 드물다. 우리가 작성한 코드의 구체적인 클래스를 모를 일이 거의 없기 때문이다.
하지만, 프레임워크나 라이브러리 등 사용하는 사람이 어떤 클래스를 만들지 모르는 경우 리플렉션을 통해 동적으로 이 문제를 해결하기 위해 많이 사용된다.

#### 리플렉션 사용 예
- 스프링
   - Dependency Injection(의존성 주입)
   - MVC 뷰에서 넘어온 데이터를 객체에 바인딩 할때
- JPA, 하이버네이트
   -  엔티티 클래스에 Setter가 없다면 리플렉션을 사용 
   - JPA 엔티티 클래스는 반드시 기본 생성자가 있어야 하는 이유도, 리플렉션 기술과 연관
- Junit
   - Junit자체에서 유틸리티를 만들어 사용
