### ISSUE TITLE
[질문] hashcode 캐싱

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/effective-java#32]
P71, **hashCode 필드의 초기값은 흔히 생성되는 객체의 해시 코드 와는 달라야 함에 유념하자** 라는 문장에서
hashCode 필드의 초기값은 지연 초기화 전략으로 만들어진 hashCode의 값으로 이해가 되고, 
흔히 생성되는 객체의 해시 코드는 무슨 의미 일까요? 더불어, 왜 달라야 하는지 예시를 통해 설명 부탁드립니다.

**Comment by im-Lily** [comment]
흔히 생성되는 객체의 hashCode는 객체를 식별할 수 있는 하나의 정수값으로 객체마다 다른 값을 가집니다.
만약 hashCode 필드의 초기값이 흔히 생성되는 객체의 hashCode와 같다면 서로 다른 객체임에도 불구하고 같은 버킷에 저장되어 해시 충돌이 발생하지 않을까라고 생각합니다.
