### ISSUE TITLE
[아이템17_질문] 자신 외에는 내부의 가변 컴포넌트에 접근할 수 없도록 한다.

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/effective-java#39]
> p. 106 자신 외에는 내부의 가변 컴포넌트에 접근할 수 없도록 한다.

해당 문장과 관련된 예시 코드를 볼 수 있을까요?

**Comment by woo00oo** [comment]
아래와 같이 Point라는 불변 객체가 Color라는 가변 필드를 가지고 있을 때,
외부 클라이언트 객체에서 가변 컴포넌트에 접근할 수 없도록 설계 해야 합니다.

그 이유는 클라이언트가 불변 객체 Color에 접근하여 상태를 변경하게 되면 Point 객체의 불변성이 깨질 수 있습니다.
따라서 불변 객체 설계 시, 자신 외에는 내부의 가변 컴포넌트에 접근할 수 없도록 한다 라는 규약이 정의 되어 있는 거 같습니다.

<img width="831" alt="스크린샷 2022-06-19 오후 9 16 19" src="https://user-images.githubusercontent.com/57715611/174480511-8c1d922b-17f4-40cc-82f8-7e0a166938f9.png">

<img width="725" alt="스크린샷 2022-06-19 오후 9 16 25" src="https://user-images.githubusercontent.com/57715611/174480516-af2203d0-9816-43f6-be04-f968b280f8ab.png">
