### ISSUE TITLE
[질문] 인스턴스 캐싱, 동반 클래스

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/effective-java#5]
[아이템 1] 내용에 대해 궁금한 점이 있어 질문 드립니다.
### 
- **인스턴스 캐싱**

`9p 새로 생성한 인스턴스를 캐싱하여 재활용하는 식으로 불필요한 객체 생성을 피할 수 있다.`
### 
위 문구에서 두 가지가 궁금합니다.

> 1, '인스턴스를 캐싱'하는 예제 코드를 볼 수 있을까요?
　
> 2. '인스턴스 캐싱'을 통해 메모리 낭비 문제를 해결할 수 있다고 하는데, 캐싱을 했을 때와 안 했을 때의 성능 차이를 가시적으로 확인할 수 있는 방법이 있나요?
### 
### 
- **동반 클래스**

`10p 이름이 "Type"인 인터페이스를 반환하는 정적 메서드가 필요하면, "Types"라는 (인스턴스화 불가인) 동반 클래스(companion class)를 만들어 그 안에 정의하는 것이 관례였다.`

> JAVA 8부터는 불필요한 부분이라고 기재되어 있기는 하나, 위 문구에 대해 동반 클래스가 사용된 예제 코드를 설명과 함께 볼 수 있을까요?

**Comment by woo00oo** [comment]
## 1. 인스턴스 캐싱

인스턴스 캐싱 예제 코드
```java
public class Font {
   private String fontFamily;
   private Integer fontSize;
}

//인스턴스 캐싱 클래스
public class FontFactory {
   private Map<String, Font> cache = new HashMap<>();

   public Font getFont(String font) {
        if (cache.containsKey(font)) {
            return cache.get(font); //기존에 있는 font라면 객체가 생성되지 않고 재사용.
        }else {
            String[] split = font.split(":");
            Font newFont = new Font(split[0], Integer.parseInt(split[1]));
            cache.put(font, newFont);
            return newFont;
        }
    }
}

//Client 
// 1. 인스턴스 캐싱 적용 X
Font font = new Font("nanum", 12);
Font font = new Font("nanum", 12);
Font font = new Font("nanum", 12);
Font font = new Font("nanum", 12);

// 매번 새로운 객체가 생성되어 힙 메모리에 축적(메모리 낭비)

// 2. 인스턴스 캐싱 적용 O
Font font = fontFactory.getFont("nanum:12");
Font font = fontFactory.getFont("nanum:12");
Font font = fontFactory.getFont("nanum:12");

// fontFamily = nanum, fontSize = 12의 상태성을 가진 Font 객체는 단 하나만 생성 되므로 메모리 낭비를 줄일 수 있다.(동일성 보장)

```
[블로그](https://steadyjay.tistory.com/15)에 인스턴스 캐싱 적용, 미적용에 대해서 테스트한 결과를 참고하시면 메모리, 시간 측면에서 성능 차이가 있다는 것을 알 수 있습니다.

---

## 2. 동반 클래스

자바 8 이전에는 디폴트 메서드와 static 메서드를 지원하지 않아 인터페이스에는 추상 메서드만 사용할 수 있었습니다.
즉, 메서드 구현은 인터페이스를 implements한 구체 클래스에서만 가능합니다.
하지만, 상황에 따라 인터페이스에도 메서드 구현이 필요한 경우(공통 로직)가 있습니다.

하나의 예시를 들자면, Ship을 만드는 비즈니스 로직이 아래와 같다고 가정하겠습니다.
1. 요청 파라미터에 대한 유효성 검사를 한다.
2. Ship에 로고를 새긴다.
3. Ship에 Color를 입힌다.
4. 컨슈머에게 완료 Email을 보낸다.

종류에 따라 Ship의 로고, Color는 다를지 몰라도 1,4은 공통적으로 처리 될 것입니다. 이런 상황은 자바 8 이전과 이후로 코드를 작성하면

```java


// 자바 8이전
public interface ShipFactory {
   Ship orderShip(String name, String email);
   Ship createShip(String type);
}
// 인터페이스 -> 추상클래스(동반클래스) -> 구체 클래스 
public abstract class DefaultShipFactroy implements ShipFactory {

   @Override
    public Ship orderShip(String name, String email) {
        validate(name, email);
        Ship ship = createShip();
        sendEmailTo(email);
        return ship;
    }

   private void validate(String name, String email) {
     //유효성 검사...
   }

   private void sendEmailTo(String email) {
     //이메일 전송...
   }

}

public class BlackShipFactory extends DefaultShipFactory{
    @Override
    public Ship createShip() {
        return new BlackShip();
    }
}

// 자바 8 이후, default메서드, static메서드 지원 private 메서드는 자바 11부터 지원.

public interface ShipFactory {

  default Ship orderShip(String name, String email){
        validate(name, email);
        Ship ship = createShip();
        sendEmailTo(email);
        return ship;
    }

  private void validate(String name, String email) {
    //유효성 검사...
  }

  private void sendEmailTo(String email) {
        //이메일 전송...
  }

public class BlackShipFactory implements ShipFactory {
   @Override
    public Ship createShip() {
        return new BlackShip();
    }
}

```

정리하자면, 자바 8 이전에는 인터페이스에 추상메서드만 정의할 수 있어 인터페이스가 제공할 수 있는 기능이 매우 한정적이였습니다. 
이런 문제점들을 해결하고자 동반 클래스를 인터페이스와 구체 클래스 사이에 두게 된 것입니다.
하지만 동반 클래스를 두게 되면 구체 클래스는 상속에 자유롭지 못하게 됩니다. 자바는 단일 상속만 지원하기 때문에 추상 클래스를 상속 받는 순간 다른 상속은 이루어질 수 없습니다. 따라서 객체 지향 설계를 할땐 상속 보다는 위임을 권장하고 있습니다.(아이템 20 추상 클래스보다는 인터페이스를 우선하라.) 
자바 8 이후에는 default 메서드, static 메서드가 지원되어 인터페이스에 많은 변화가 생겼고 추상 클래스로 제공된 메서드들이 대다수 deprecated 되었습니다.

**Comment by woo00oo** [comment]
자바 상속 위임 관련
https://sorjfkrh5078.tistory.com/m/282
