### ISSUE TITLE
[공유] 싱글턴 객체를 클라이언트가 테스트하기 어려운 이유.

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/effective-java#7]
Item3 23p에 나와있는 아래 문구에 대해서 예제 코드를 통해 조금 더 자세히 정리하고자 한다.

> **클래스를 싱글턴으로 만들면 이를 사용하는 클라이언트를 테스트하기 어려워질 수 있다**. 타입을 인터페이스로 정의한 다음 그 인터페이스를 구현해서 만든 싱글턴이 아니라면 싱글턴 인스턴스를 가짜(mock) 구현으로 대체할 수 없기 때문이다.

아래와 같이 Elvis라는 싱글턴 객체가 있다.

```java

public class Elvis {

    public static final Elvis INSTANCE = new Elvis();

    private Elvis() {}

    public void leaveTheBuilding() {
        System.out.println("Whoa baby, I`m outta here!");
    }

    public void sing() {
        System.out.println("I`ll have a blue~ Christmas without you~");
    }

}

```

Elvis를 의존하고 있는 Concert라는 클래스가 있고 이 클래스에 대해서 테스트 코드를 작성해야 한다고 가정해보자.

```java

public class Concert {

    private boolean lightsOn;

    private boolean mainStateOpen;

    private Elvis elvis;

    public Concert(Elvis elvis) {
        this.elvis = elvis;
    }

    public void perform() {
        this.mainStateOpen = true;
        this.lightsOn = true;
        elvis.sing();
    }

    public boolean isLightsOn() {
        return this.lightsOn;
    }

    public boolean isMainStateOpen() {
        return this.mainStateOpen;
    }
}

---

//테스트 코드
class ConcertTest {

    @Test
    void perform() {
        Concert concert = new Concert(Elvis.INSTANCE);
        concert.perform();

        assertTrue(concert.isLightsOn());
        assertTrue(concert.isMainStateOpen());
    }

}

```

만약, Elvis라는 객체가 생성 비용이 비싼 객체라면 테스트를 실행하는데 아주 비 효율적이다. 
(Elvis라는 객체가 외부 통신, DB통신 등등 비용이 많이 드는 객체라면)

개발자는 Concert라는 객체(클라이언트)의 테스트 코드를 작성하기 위해 Elvis라는 객체를 DI 해야 하는데 Elvis는 싱글턴 객체임으로 
테스트 코드가 실행될 때마다 비용이 많이드는 Evlis 싱글턴 객체를 주입 받을 수 밖에 없다.

따라서 책에서는 인터페이스를 구현해서 가짜(mock) 구현으로 대체할 수 있다고 말하고 있다.
위의 코드를 리펙토링 하면

```java

public interface IElvis {

    void leaveTheBuilding();

    void sing();

}

// 가짜(Mock) 객체
public class MockElvis implements IElvis{

   ...생략

    @Override
    public void sing() {
        System.out.println("가짜 객체입니다.");
    }
}

//기존 싱글턴 객체
public class Elvis implements IElvis{

    public static final Elvis INSTANCE = new Elvis();

    private Elvis() {}

    @Override
    public void leaveTheBuilding() {
        System.out.println("Whoa baby, I`m outta here!");
    }

    @Override
    public void sing() {
        System.out.println("I`ll have a blue~ Christmas without you~");
    }

}
//클라이언트 
public class Concert {

    ...생략

    private IElvis elvis; //인터페이스 타입으로 변경

    public Concert(IElvis elvis) {
        this.elvis = elvis;
    }
   
    ...생략 

}

```

이와 같이 인터페이스를 정의하고 Concert의 Elvis 타입을 인터페이스 타입으로 변경하면 
테스트 코드 작성시 Mock 객체를 주입시킬 수 있다.

```java

class ConcertTest {

    @Test
    void perform() {
        Concert concert = new Concert(new MockElvis());
        concert.perform();

        assertTrue(concert.isLightsOn());
        assertTrue(concert.isMainStateOpen());
    }

}

```

결론.
> Mock 객체를 주입 받아 적은 비용으로 테스트 코드를 실행할 수 있다. 또, 테스트 코드를 작성하는데 수월하다.

---

요즘 같은 스프링 부트 환경에서는 Mockito 프레임워크가 외부 라이브러리에 default로 주입되어 있어 Mocking 하는데 훨씬 더 효율적이다.

```java

@ExtendWith(MockitoExtension.class)
class ConcertTest {

    @Mock // 어노테이션만 선언해주면 Mockito가 자동으로 가짜 객체를 주입시켜준다.
    Elvis elvis;

    @Test
    void perform() {
        Concert concert = new Concert(elvis);
        concert.perform();

        assertTrue(concert.isLightsOn());
        assertTrue(concert.isMainStateOpen());
    }

}

```

**Comment by im-Lily** [comment]
“ 인터페이스를 구현해서 가짜(mock) 구현으로 대체할 수 있다고 말하고 있다.” 이 부분이 이해가 잘 안됩니다

테스트할 때마다 비용이 많이 드는 싱글톤 객체를 주입받는 것이 비효율적이라 기존 싱글톤 객체는 그대로 두고, 인터페이스를 구현해서 새로운 가짜 객체를 만드는 게 맞나요?

mock 객체를 주입받아 테스트를 진행하면 적은 비용으로 테스트를 진행할 수 있는지 어떻게 알 수 있나요?

**Comment by woo00oo** [comment]
mock 객체를 사용하면 가시적으로 어떤 부분이 효율적인지에 대해 궁금하신 거 같아 아래 예시를 통해 설명해드리겠습니다.

예를 들어,
KakaopayService라는 객체가 있고 이 객체는 KakaopayRepository 라는 객체를 의존성 주입을 받고 있습니다.
여기서 저는 KakopayService 클래스의 단위 테스트를 작성하고 싶고 서비스 계층의 로직을 테스트 하고 싶습니다.
서비스 계층 로직을 수행하는데 Repository를 호출하는 경우가 있을 것이고 Repository를 호출하면 DB와도 커넥션을 맺어야하고 SQL을 날리는등 여러 비용이 발생하게 됩니다. 물론 인메모리 DB 설정으로 테스트를 할 수도 있겠지만, JPA JDBC 등 여러 외부 기술들을 사용하여 테스트를 진행하게 됩니다.(이런 비용들 때문에 테스트 코드 실행 속도가 느려지게 됨)
하지만, 여기서 저의 관심사는 Repository 계층의 테스트가 아니라 단순히 서비스 계층의 단위 테스트를 실행하는 것입니다.
서비스 계층은 특정 기술에 의존하지 않고 순수 자바 코드로 구성되어 있는데 Mock 객체를 사용하지 않으면 테스트 코드를 실행하는데 위와 같은 불필요한 비용(DB 연동 기술 의존)이 발생하게 됩니다.
이런 경우에 Mockito 라는 기술을 사용하는데 아래와 같이 가짜 객체를 주입받아 가짜 객체의 메소드들을 컨트롤할 수 있게 되어 서비스 계층의 로직에 대해서만 포커싱을 맞추어 테스트 코드를 작성할 수 있습니다.

```java

@Mock
KakaopayRepository kakaopayRepository;

@Test
void test() {
   Transact transact = new Transact(); //내가 생성한 객체
   given(kakaopayRepository.findById(any()).willReturn(transact)); // "findById 메소드를 호출하면 transact이라는 객체를 반환해줘"라는 로직
   //.. 서비스 로직 테스트 코드 
}
```

이외에도 Mock Session, Mock Cookie, MockHttpServletRequest 등 가짜 객체를 통하여 비용이 드는 부분을 해결할 수 있습니다.

책에 나온 내용으로는 Mockito라는 프레임워크를 따로 언급 하지는 않고 있고, 싱글톤으로 구성되어 있는 객체의 경우 테스트 코드를 작성할때 Mock 객체를 제공하기가 어려우니 인터페이스를 구현하여 Mock 객체를 구현하여 대체할 수 있다 라고 설명하고 있는거 같습니다.
