### ISSUE TITLE
[공유] 커스텀 Exception은 언제 써야 할까?

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/effective-java#8]
백기선님 강의를 듣다가 **자바에서 제공하는 표준 RuntimeException을 적극 사용하고 그 외에 Custom Exception 사용을 권장한다** 라는 말이 의아하여 Custom Exception은 도대체 언제 사용해야 하는지에 구글링을 조금 더 해보았습니다. 사용자 정의 예외를 두고 의견 차이는 많은 거 같습니다.

[참고자료](https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/)

**Comment by heizleKoo** [comment]
상황에 따라 적절한 Exception을, 구현한 목적에 맞게 사용하는게 베스트라는 거네요 기억해두고 써야겠습니다 😊
